User.create(first_name: "Anthony", last_name: "Chien", username: "antchien@gmail.com", password: "123456", profile_pic: open("http://images2.wikia.nocookie.net/__cb20111103182547/poohadventures/images/3/3b/LaunchpadMcQuack.gif"))
User.create(first_name: "Emil", last_name: "Lee", username: "uciehlee@gmail.com", password: "123456", profile_pic: open("http://static3.wikia.nocookie.net/__cb20130923024408/doblaje/es/images/8/85/Huey.jpg"))
User.create(first_name: "Kevin", last_name: "Li", username: "evilkartman@gmail.com", password: "123456", profile_pic: open("http://static2.wikia.nocookie.net/__cb20130829030938/capcomdatabase/images/1/13/DuckTalesScrooge.png"))
User.create(first_name: "Brian", last_name: "Deane", username: "beane@gmail.com", password: "123456", profile_pic: open("http://static1.wikia.nocookie.net/__cb20130923024521/doblaje/es/images/f/f9/Dewey_Duck.jpg"))
User.create(first_name: "Sam", last_name: "Tran", username: "simplyxsam@gmail.com", password: "123456", profile_pic: open("http://images1.wikia.nocookie.net/__cb20091223024523/disney/images/9/99/AMELIA.jpg"))
User.create(first_name: "Spongebob", last_name: "Squarepants", username: "sbsp@gmail.com", password: "123456", profile_pic: open("http://images4.wikia.nocookie.net/__cb20120807051902/poohadventures/images/a/a7/Spongebob009.gif"))
User.create(first_name: "Arnold", last_name: "Schwarz", username: "pahmpyouup@gmail.com", password: "123456", profile_pic: open("https://s3.amazonaws.com/yibs-dev/users/profile_pics/000/000/009/small/arnold.jpeg"))
Friendship.create(out_friend_id: 1, in_friend_id: 2)
Friendship.create(out_friend_id: 1, in_friend_id: 3)
Friendship.create(out_friend_id: 1, in_friend_id: 4)
Friendship.create(out_friend_id: 2, in_friend_id: 1)
Friendship.create(out_friend_id: 3, in_friend_id: 1)
Friendship.create(out_friend_id: 2, in_friend_id: 3)
Friendship.create(out_friend_id: 2, in_friend_id: 4)
Friendship.create(out_friend_id: 3, in_friend_id: 2)

Bet.create(user_id:1, terms:"he can program chess faster", wager:"eat everything in the App Academy mini-fridge", status:"pending", private:false)
BetParticipation.create(bet_id:1, user_id:1, status:'accepted')
BetParticipation.create(bet_id:1, user_id:2, status:"pending")
Bet.create(user_id:1, terms:"he can lose 20 pounds first", wager:"buy winner dinner at per se", status:"pending", private:false)
BetParticipation.create(bet_id:2, user_id:1, status:'accepted')
BetParticipation.create(bet_id:2, user_id:2, status:'accepted')
BetParticipation.create(bet_id:2, user_id:3, status:'pending')
BetParticipation.create(bet_id:2, user_id:4, status:'declined')
BetParticipation.create(bet_id:2, user_id:5, status:'accepted')
Comment.create(user_id:2, bet_id:2, text:"what's chess?")
Comment.create(user_id:3, bet_id:2, text:"hey guys can i play?")