# User.create(first_name: "Anthony", last_name: "Chien", username: "antchien@gmail.com", password: "123456", profile_pic: open("https://scontent-a.xx.fbcdn.net/hphotos-ash2/398405_10101052802172813_1360791293_n.jpg"))
# User.create(first_name: "Emil", last_name: "Lee", username: "uciehlee@gmail.com", password: "123456", profile_pic: open("https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/s160x160/1175326_10102016873650891_923023494_a.jpg"))
# User.create(first_name: "Kevin", last_name: "Li", username: "evilkartman@gmail.com", password: "123456", profile_pic: open("https://fbcdn-profile-a.akamaihd.net/hprofile-ak-prn2/c1.21.179.179/s160x160/1376377_10101896618014124_1899057977_a.jpg"))
# User.create(first_name: "Brian", last_name: "Deane", username: "beane@gmail.com", password: "123456", profile_pic: open("http://cf.badassdigest.com/_uploads/images/30792/arnold-schwarzenegger-movies__span.jpg"))
# User.create(first_name: "Sam", last_name: "Tran", username: "simplyxsam@gmail.com", password: "123456", profile_pic: open("http://assets.nydailynews.com/polopoly_fs/1.952216!/img/httpImage/image.jpg_gen/derivatives/landscape_635/alg-minka-kelly-jpg.jpg"))
# User.create(first_name: "Spongebob", last_name: "Squarepants", username: "sbsp@gmail.com", password: "123456", profile_pic: open("http://musclememory.com/images/recent/SchwarzeneggerArnold-Zeller.jpg"))
# User.create(first_name: "Arnold", last_name: "Schwarz", username: "pahmpyouup@gmail.com", password: "123456", profile_pic: open("https://s3.amazonaws.com/yibs-dev/users/profile_pics/000/000/009/small/arnold.jpeg"))
# User.create(first_name: "batman", last_name: "batman", username: "batman@gmail.com", password: "123456", profile_pic: open("http://www.tenniswood.co.uk/wp-content/uploads/2010/01/design-fetish-no-photo-facebook-1.jpg"))
# User.create(username:"antcheee@gmail.com", password:"123456", first_name:"antony", last_name: "chen")
# User.create(username:"antwan@gmail.com", password:"123456", first_name:"antwan", last_name: "chin")
# User.create(username:"antwany@gmail.com", password:"123456", first_name:"antwany", last_name: "chin")
# User.create(username:"antchin@gmail.com", password:"123456", first_name:"antigua", last_name: "cooties")
# 
# Friendship.create(out_friend_id: 1, in_friend_id: 2, pending_flag: false)
# Friendship.create(out_friend_id: 1, in_friend_id: 3, pending_flag: false)
# Friendship.create(out_friend_id: 1, in_friend_id: 4, pending_flag: true)
# Friendship.create(out_friend_id: 1, in_friend_id: 5, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 1, pending_flag: false)
# Friendship.create(out_friend_id: 3, in_friend_id: 1, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 3, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 4, pending_flag: true)
# Friendship.create(out_friend_id: 3, in_friend_id: 2, pending_flag: false)
# Friendship.create(out_friend_id: 7, in_friend_id: 1, pending_flag: true)
# Friendship.create(out_friend_id: 6, in_friend_id: 1, pending_flag: true)
# Friendship.create(out_friend_id: 5, in_friend_id: 1, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 9, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 10, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 11, pending_flag: false)
# Friendship.create(out_friend_id: 2, in_friend_id: 12, pending_flag: false)
# Friendship.create(out_friend_id: 9, in_friend_id: 2, pending_flag: false)
# Friendship.create(out_friend_id: 10, in_friend_id: 2, pending_flag: false)
# Friendship.create(out_friend_id: 11, in_friend_id: 2, pending_flag: false)
# Friendship.create(out_friend_id: 12, in_friend_id: 2, pending_flag: false)
# 
# Bet.create(user_id:1, terms:"he can program chess faster", wager:"eat everything in the App Academy mini-fridge", status:"pending", private:false)
# BetParticipation.create(bet_id:1, user_id:1, status:'accepted')
# BetParticipation.create(bet_id:1, user_id:2, status:"pending")
# Bet.create(user_id:1, terms:"he can lose 20 pounds first", wager:"buy winner dinner at per se", status:"pending", private:false)
# BetParticipation.create(bet_id:2, user_id:1, status:'accepted')
# BetParticipation.create(bet_id:2, user_id:2, status:'accepted')
# BetParticipation.create(bet_id:2, user_id:3, status:'pending')
# BetParticipation.create(bet_id:2, user_id:4, status:'declined')
# BetParticipation.create(bet_id:2, user_id:5, status:'accepted')
# Comment.create(user_id:2, bet_id:2, text:"what's chess?")
# Comment.create(user_id:3, bet_id:2, text:"hey guys can i play?")
# Bet.create(user_id:2, terms:"he can erase Brian's project by the end of the day without him noticing", wager:"wrestle tommy", status:"in play", private:false)
# BetParticipation.create(bet_id:3, user_id:4, status:'accepted')
# BetParticipation.create(bet_id:3, user_id:2, status:'accepted')
# Comment.create(user_id:7, bet_id:3, text:"hi guys.")